// Generated by gencpp from file kortex_tools/SaveData.msg
// DO NOT EDIT!


#ifndef KORTEX_TOOLS_MESSAGE_SAVEDATA_H
#define KORTEX_TOOLS_MESSAGE_SAVEDATA_H

#include <ros/service_traits.h>


#include <kortex_tools/SaveDataRequest.h>
#include <kortex_tools/SaveDataResponse.h>


namespace kortex_tools
{

struct SaveData
{

typedef SaveDataRequest Request;
typedef SaveDataResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SaveData
} // namespace kortex_tools


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kortex_tools::SaveData > {
  static const char* value()
  {
    return "1497dd37643804fd87f9722c47ea18be";
  }

  static const char* value(const ::kortex_tools::SaveData&) { return value(); }
};

template<>
struct DataType< ::kortex_tools::SaveData > {
  static const char* value()
  {
    return "kortex_tools/SaveData";
  }

  static const char* value(const ::kortex_tools::SaveData&) { return value(); }
};


// service_traits::MD5Sum< ::kortex_tools::SaveDataRequest> should match
// service_traits::MD5Sum< ::kortex_tools::SaveData >
template<>
struct MD5Sum< ::kortex_tools::SaveDataRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kortex_tools::SaveData >::value();
  }
  static const char* value(const ::kortex_tools::SaveDataRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kortex_tools::SaveDataRequest> should match
// service_traits::DataType< ::kortex_tools::SaveData >
template<>
struct DataType< ::kortex_tools::SaveDataRequest>
{
  static const char* value()
  {
    return DataType< ::kortex_tools::SaveData >::value();
  }
  static const char* value(const ::kortex_tools::SaveDataRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kortex_tools::SaveDataResponse> should match
// service_traits::MD5Sum< ::kortex_tools::SaveData >
template<>
struct MD5Sum< ::kortex_tools::SaveDataResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kortex_tools::SaveData >::value();
  }
  static const char* value(const ::kortex_tools::SaveDataResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kortex_tools::SaveDataResponse> should match
// service_traits::DataType< ::kortex_tools::SaveData >
template<>
struct DataType< ::kortex_tools::SaveDataResponse>
{
  static const char* value()
  {
    return DataType< ::kortex_tools::SaveData >::value();
  }
  static const char* value(const ::kortex_tools::SaveDataResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KORTEX_TOOLS_MESSAGE_SAVEDATA_H
