// Generated by gencpp from file kortex_tools/SaveDataResponse.msg
// DO NOT EDIT!


#ifndef KORTEX_TOOLS_MESSAGE_SAVEDATARESPONSE_H
#define KORTEX_TOOLS_MESSAGE_SAVEDATARESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kortex_tools
{
template <class ContainerAllocator>
struct SaveDataResponse_
{
  typedef SaveDataResponse_<ContainerAllocator> Type;

  SaveDataResponse_()
    : Success(0)  {
    }
  SaveDataResponse_(const ContainerAllocator& _alloc)
    : Success(0)  {
  (void)_alloc;
    }



   typedef int64_t _Success_type;
  _Success_type Success;





  typedef boost::shared_ptr< ::kortex_tools::SaveDataResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kortex_tools::SaveDataResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SaveDataResponse_

typedef ::kortex_tools::SaveDataResponse_<std::allocator<void> > SaveDataResponse;

typedef boost::shared_ptr< ::kortex_tools::SaveDataResponse > SaveDataResponsePtr;
typedef boost::shared_ptr< ::kortex_tools::SaveDataResponse const> SaveDataResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kortex_tools::SaveDataResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kortex_tools::SaveDataResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kortex_tools::SaveDataResponse_<ContainerAllocator1> & lhs, const ::kortex_tools::SaveDataResponse_<ContainerAllocator2> & rhs)
{
  return lhs.Success == rhs.Success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kortex_tools::SaveDataResponse_<ContainerAllocator1> & lhs, const ::kortex_tools::SaveDataResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kortex_tools

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::kortex_tools::SaveDataResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kortex_tools::SaveDataResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kortex_tools::SaveDataResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kortex_tools::SaveDataResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kortex_tools::SaveDataResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kortex_tools::SaveDataResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kortex_tools::SaveDataResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f5ac40719150c2d44ad14cf750430183";
  }

  static const char* value(const ::kortex_tools::SaveDataResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf5ac40719150c2d4ULL;
  static const uint64_t static_value2 = 0x4ad14cf750430183ULL;
};

template<class ContainerAllocator>
struct DataType< ::kortex_tools::SaveDataResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kortex_tools/SaveDataResponse";
  }

  static const char* value(const ::kortex_tools::SaveDataResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kortex_tools::SaveDataResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 Success\n"
"\n"
;
  }

  static const char* value(const ::kortex_tools::SaveDataResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kortex_tools::SaveDataResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SaveDataResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kortex_tools::SaveDataResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kortex_tools::SaveDataResponse_<ContainerAllocator>& v)
  {
    s << indent << "Success: ";
    Printer<int64_t>::stream(s, indent + "  ", v.Success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KORTEX_TOOLS_MESSAGE_SAVEDATARESPONSE_H
