// Generated by gencpp from file camera_robot_interaction/Movement.msg
// DO NOT EDIT!


#ifndef CAMERA_ROBOT_INTERACTION_MESSAGE_MOVEMENT_H
#define CAMERA_ROBOT_INTERACTION_MESSAGE_MOVEMENT_H

#include <ros/service_traits.h>


#include <camera_robot_interaction/MovementRequest.h>
#include <camera_robot_interaction/MovementResponse.h>


namespace camera_robot_interaction
{

struct Movement
{

typedef MovementRequest Request;
typedef MovementResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Movement
} // namespace camera_robot_interaction


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::camera_robot_interaction::Movement > {
  static const char* value()
  {
    return "4787e27e3721f1f2004cf17997b3e3ae";
  }

  static const char* value(const ::camera_robot_interaction::Movement&) { return value(); }
};

template<>
struct DataType< ::camera_robot_interaction::Movement > {
  static const char* value()
  {
    return "camera_robot_interaction/Movement";
  }

  static const char* value(const ::camera_robot_interaction::Movement&) { return value(); }
};


// service_traits::MD5Sum< ::camera_robot_interaction::MovementRequest> should match
// service_traits::MD5Sum< ::camera_robot_interaction::Movement >
template<>
struct MD5Sum< ::camera_robot_interaction::MovementRequest>
{
  static const char* value()
  {
    return MD5Sum< ::camera_robot_interaction::Movement >::value();
  }
  static const char* value(const ::camera_robot_interaction::MovementRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::camera_robot_interaction::MovementRequest> should match
// service_traits::DataType< ::camera_robot_interaction::Movement >
template<>
struct DataType< ::camera_robot_interaction::MovementRequest>
{
  static const char* value()
  {
    return DataType< ::camera_robot_interaction::Movement >::value();
  }
  static const char* value(const ::camera_robot_interaction::MovementRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::camera_robot_interaction::MovementResponse> should match
// service_traits::MD5Sum< ::camera_robot_interaction::Movement >
template<>
struct MD5Sum< ::camera_robot_interaction::MovementResponse>
{
  static const char* value()
  {
    return MD5Sum< ::camera_robot_interaction::Movement >::value();
  }
  static const char* value(const ::camera_robot_interaction::MovementResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::camera_robot_interaction::MovementResponse> should match
// service_traits::DataType< ::camera_robot_interaction::Movement >
template<>
struct DataType< ::camera_robot_interaction::MovementResponse>
{
  static const char* value()
  {
    return DataType< ::camera_robot_interaction::Movement >::value();
  }
  static const char* value(const ::camera_robot_interaction::MovementResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAMERA_ROBOT_INTERACTION_MESSAGE_MOVEMENT_H
