// Generated by gencpp from file camera_robot_interaction/MovementResponse.msg
// DO NOT EDIT!


#ifndef CAMERA_ROBOT_INTERACTION_MESSAGE_MOVEMENTRESPONSE_H
#define CAMERA_ROBOT_INTERACTION_MESSAGE_MOVEMENTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace camera_robot_interaction
{
template <class ContainerAllocator>
struct MovementResponse_
{
  typedef MovementResponse_<ContainerAllocator> Type;

  MovementResponse_()
    : Success(0)
    , gripper_fb(0.0)  {
    }
  MovementResponse_(const ContainerAllocator& _alloc)
    : Success(0)
    , gripper_fb(0.0)  {
  (void)_alloc;
    }



   typedef int64_t _Success_type;
  _Success_type Success;

   typedef float _gripper_fb_type;
  _gripper_fb_type gripper_fb;





  typedef boost::shared_ptr< ::camera_robot_interaction::MovementResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::camera_robot_interaction::MovementResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MovementResponse_

typedef ::camera_robot_interaction::MovementResponse_<std::allocator<void> > MovementResponse;

typedef boost::shared_ptr< ::camera_robot_interaction::MovementResponse > MovementResponsePtr;
typedef boost::shared_ptr< ::camera_robot_interaction::MovementResponse const> MovementResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::camera_robot_interaction::MovementResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::camera_robot_interaction::MovementResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::camera_robot_interaction::MovementResponse_<ContainerAllocator1> & lhs, const ::camera_robot_interaction::MovementResponse_<ContainerAllocator2> & rhs)
{
  return lhs.Success == rhs.Success &&
    lhs.gripper_fb == rhs.gripper_fb;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::camera_robot_interaction::MovementResponse_<ContainerAllocator1> & lhs, const ::camera_robot_interaction::MovementResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace camera_robot_interaction

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::camera_robot_interaction::MovementResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::camera_robot_interaction::MovementResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera_robot_interaction::MovementResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera_robot_interaction::MovementResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera_robot_interaction::MovementResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera_robot_interaction::MovementResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::camera_robot_interaction::MovementResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0baab5e2da097063283a0661272a622e";
  }

  static const char* value(const ::camera_robot_interaction::MovementResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0baab5e2da097063ULL;
  static const uint64_t static_value2 = 0x283a0661272a622eULL;
};

template<class ContainerAllocator>
struct DataType< ::camera_robot_interaction::MovementResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "camera_robot_interaction/MovementResponse";
  }

  static const char* value(const ::camera_robot_interaction::MovementResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::camera_robot_interaction::MovementResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 Success\n"
"float32 gripper_fb\n"
"\n"
;
  }

  static const char* value(const ::camera_robot_interaction::MovementResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::camera_robot_interaction::MovementResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Success);
      stream.next(m.gripper_fb);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MovementResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::camera_robot_interaction::MovementResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::camera_robot_interaction::MovementResponse_<ContainerAllocator>& v)
  {
    s << indent << "Success: ";
    Printer<int64_t>::stream(s, indent + "  ", v.Success);
    s << indent << "gripper_fb: ";
    Printer<float>::stream(s, indent + "  ", v.gripper_fb);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAMERA_ROBOT_INTERACTION_MESSAGE_MOVEMENTRESPONSE_H
