// Generated by gencpp from file kortex_movement/cartesian_movement.msg
// DO NOT EDIT!


#ifndef KORTEX_MOVEMENT_MESSAGE_CARTESIAN_MOVEMENT_H
#define KORTEX_MOVEMENT_MESSAGE_CARTESIAN_MOVEMENT_H

#include <ros/service_traits.h>


#include <kortex_movement/cartesian_movementRequest.h>
#include <kortex_movement/cartesian_movementResponse.h>


namespace kortex_movement
{

struct cartesian_movement
{

typedef cartesian_movementRequest Request;
typedef cartesian_movementResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct cartesian_movement
} // namespace kortex_movement


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kortex_movement::cartesian_movement > {
  static const char* value()
  {
    return "527d545043520e6207cc8929405c4e9e";
  }

  static const char* value(const ::kortex_movement::cartesian_movement&) { return value(); }
};

template<>
struct DataType< ::kortex_movement::cartesian_movement > {
  static const char* value()
  {
    return "kortex_movement/cartesian_movement";
  }

  static const char* value(const ::kortex_movement::cartesian_movement&) { return value(); }
};


// service_traits::MD5Sum< ::kortex_movement::cartesian_movementRequest> should match
// service_traits::MD5Sum< ::kortex_movement::cartesian_movement >
template<>
struct MD5Sum< ::kortex_movement::cartesian_movementRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kortex_movement::cartesian_movement >::value();
  }
  static const char* value(const ::kortex_movement::cartesian_movementRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kortex_movement::cartesian_movementRequest> should match
// service_traits::DataType< ::kortex_movement::cartesian_movement >
template<>
struct DataType< ::kortex_movement::cartesian_movementRequest>
{
  static const char* value()
  {
    return DataType< ::kortex_movement::cartesian_movement >::value();
  }
  static const char* value(const ::kortex_movement::cartesian_movementRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kortex_movement::cartesian_movementResponse> should match
// service_traits::MD5Sum< ::kortex_movement::cartesian_movement >
template<>
struct MD5Sum< ::kortex_movement::cartesian_movementResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kortex_movement::cartesian_movement >::value();
  }
  static const char* value(const ::kortex_movement::cartesian_movementResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kortex_movement::cartesian_movementResponse> should match
// service_traits::DataType< ::kortex_movement::cartesian_movement >
template<>
struct DataType< ::kortex_movement::cartesian_movementResponse>
{
  static const char* value()
  {
    return DataType< ::kortex_movement::cartesian_movement >::value();
  }
  static const char* value(const ::kortex_movement::cartesian_movementResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KORTEX_MOVEMENT_MESSAGE_CARTESIAN_MOVEMENT_H
