// Generated by gencpp from file kortex_movement/cartesian_movementResponse.msg
// DO NOT EDIT!


#ifndef KORTEX_MOVEMENT_MESSAGE_CARTESIAN_MOVEMENTRESPONSE_H
#define KORTEX_MOVEMENT_MESSAGE_CARTESIAN_MOVEMENTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kortex_movement
{
template <class ContainerAllocator>
struct cartesian_movementResponse_
{
  typedef cartesian_movementResponse_<ContainerAllocator> Type;

  cartesian_movementResponse_()
    : output(false)  {
    }
  cartesian_movementResponse_(const ContainerAllocator& _alloc)
    : output(false)  {
  (void)_alloc;
    }



   typedef uint8_t _output_type;
  _output_type output;





  typedef boost::shared_ptr< ::kortex_movement::cartesian_movementResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kortex_movement::cartesian_movementResponse_<ContainerAllocator> const> ConstPtr;

}; // struct cartesian_movementResponse_

typedef ::kortex_movement::cartesian_movementResponse_<std::allocator<void> > cartesian_movementResponse;

typedef boost::shared_ptr< ::kortex_movement::cartesian_movementResponse > cartesian_movementResponsePtr;
typedef boost::shared_ptr< ::kortex_movement::cartesian_movementResponse const> cartesian_movementResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kortex_movement::cartesian_movementResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kortex_movement::cartesian_movementResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kortex_movement::cartesian_movementResponse_<ContainerAllocator1> & lhs, const ::kortex_movement::cartesian_movementResponse_<ContainerAllocator2> & rhs)
{
  return lhs.output == rhs.output;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kortex_movement::cartesian_movementResponse_<ContainerAllocator1> & lhs, const ::kortex_movement::cartesian_movementResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kortex_movement

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::kortex_movement::cartesian_movementResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kortex_movement::cartesian_movementResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kortex_movement::cartesian_movementResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kortex_movement::cartesian_movementResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kortex_movement::cartesian_movementResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kortex_movement::cartesian_movementResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kortex_movement::cartesian_movementResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d5fa62db5c86ed745052c3b25d12f430";
  }

  static const char* value(const ::kortex_movement::cartesian_movementResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd5fa62db5c86ed74ULL;
  static const uint64_t static_value2 = 0x5052c3b25d12f430ULL;
};

template<class ContainerAllocator>
struct DataType< ::kortex_movement::cartesian_movementResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kortex_movement/cartesian_movementResponse";
  }

  static const char* value(const ::kortex_movement::cartesian_movementResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kortex_movement::cartesian_movementResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool output\n"
"\n"
;
  }

  static const char* value(const ::kortex_movement::cartesian_movementResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kortex_movement::cartesian_movementResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.output);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct cartesian_movementResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kortex_movement::cartesian_movementResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kortex_movement::cartesian_movementResponse_<ContainerAllocator>& v)
  {
    s << indent << "output: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.output);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KORTEX_MOVEMENT_MESSAGE_CARTESIAN_MOVEMENTRESPONSE_H
