(cl:in-package camera_robot_interaction-srv)
(cl:export '(R11-VAL
          R11
          R12-VAL
          R12
          R13-VAL
          R13
          R14-VAL
          R14
          R21-VAL
          R21
          R22-VAL
          R22
          R23-VAL
          R23
          R24-VAL
          R24
          R31-VAL
          R31
          R32-VAL
          R32
          R33-VAL
          R33
          R34-VAL
          R34
          GRIPPER-VAL
          GRIPPER
          ROTATE-VAL
          ROTATE
          REST_POS-VAL
          REST_POS
          SUCCESS-VAL
          SUCCESS
          GRIPPER_FB-VAL
          GRIPPER_FB
))